import pygame


class SeaFloor(pygame.sprite.Sprite):
    def __init__(self, width):
        super().__init__()
        self.image = pygame.surface.Surface(64*25)

        self.sand_convex = pygame.image.load("images/fishTile_025.png")
        self.sand_convex_rect = sand_convex.get_rect()
        self.sand_concave = pygame.image.load("images/fishTile_024.png")
        self.sand_concave_rect = sand_concave.get_rect()

        self.dead_fish = pygame.image.load("images/kenney_fishpack/PNG/Default size/fishTile_099.png")
        self.dead_fish_rect = dead_fish.get_rect()
        self.green_seaweed = pygame.image.load("images/kenney_fishpack/PNG/Default size/fishTile_028.png")
        self.green_seaweed_rect = green_seaweed.get_rect()
        self.purple_seaweed = pygame.image.load("images/kenney_fishpack/PNG/Default size/fishTile_017.png")
        self.purple_seaweed_rect = purple_seaweed.get_rect()
        self.rock = pygame.image.load("images/kenney_fishpack/PNG/Default size/fishTile_084.png")
        self.rock_rect = rock.get_rect()

    def blitme(self):
        background.blit(sand_convex, (64, 832))
        background.blit(sand_convex, (192, 832))
        background.blit(sand_convex, (320, 832))
        background.blit(sand_convex, (448, 832))
        background.blit(sand_convex, (576, 832))
        background.blit(sand_convex, (704, 832))
        background.blit(sand_convex, (832, 832))
        background.blit(sand_convex, (960, 832))
        background.blit(sand_convex, (1088, 832))
        background.blit(sand_convex, (1216, 832))
        background.blit(sand_convex, (1344, 832))
        background.blit(sand_convex, (1472, 832))
        background.blit(sand_concave, (0, 832))
        background.blit(sand_concave, (128, 832))
        background.blit(sand_concave, (256, 832))
        background.blit(sand_concave, (384, 832))
        background.blit(sand_concave, (512, 832))
        background.blit(sand_concave, (640, 832))
        background.blit(sand_concave, (768, 832))
        background.blit(sand_concave, (896, 832))
        background.blit(sand_concave, (1024, 832))
        background.blit(sand_concave, (1152, 832))
        background.blit(sand_concave, (1280, 832))
        background.blit(sand_concave, (1408, 832))
        background.blit(sand_concave, (1536, 832))
        background.blit(green_seaweed, (128, 777))
        background.blit(green_seaweed, (1088, 771))
        background.blit(purple_seaweed, (512, 777))
        background.blit(dead_fish, (756, 850))
        background.blit(rock, (5, 777))
        background.blit(rock, (1408, 777))